# Generated by Django 5.2.1 on 2025-08-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('repost', 'Repost'), ('donation', 'Donation'), ('report_received', 'Report Received'), ('post_removed', 'Post Removed for Multiple Reports'), ('appeal_approved', 'Appeal Approved'), ('appeal_rejected', 'Appeal Rejected'), ('art_verified', 'Art Verified')], max_length=20),
        ),
    ]
