# Generated by Django 5.2.1 on 2025-06-03 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_reposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_repost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='original_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts_as_post', to='posts.post'),
        ),
    ]
