# Generated by Django 5.2.1 on 2025-06-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_is_repost_post_original_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_repost',
        ),
        migrations.RemoveField(
            model_name='post',
            name='original_post',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('original', 'Original Post'), ('repost', 'Repost'), ('quote', 'Quote Post')], default='original', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='referenced_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
