# Generated by Django 5.2.1 on 2025-06-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='materialized_path',
            field=models.CharField(db_index=True, default='/', max_length=255),
        ),
    ]
