# Generated by Django 5.2.1 on 2025-06-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_human_drawing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('original', 'Original Post'), ('repost', 'Repost'), ('quote', 'Quote Post'), ('human_drawing', 'Human Drawing')], default='original', max_length=15),
        ),
    ]
