# Generated by Django 5.2.1 on 2025-06-09 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_is_human_drawing_post_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='referenced_comment',
            field=models.ForeignKey('Comment', on_delete=models.SET_NULL, null=True, blank=True, related_name='reposts'),
        ),
    ] 