# Generated by Django 5.2.1 on 2025-06-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_referenced_comment'),
        ('posts', '0012_alter_comment_options_and_more'),
    ]

    operations = [
    ]
