# Generated by Django 5.2.1 on 2025-06-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_merge_20250609_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.JSONField(blank=True, default=list),
        ),
    ] 