# Generated by Django 5.2.1 on 2025-06-09 19:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('repost', 'Repost'), ('quote', 'Quote')], default='post', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='referenced_post',
            field=models.ForeignKey('posts.Post', blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='referenced_comment',
            field=models.ForeignKey('posts.Comment', blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
