# Generated by Django 5.2.1 on 2025-06-09 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20250609_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reposts',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reposts',
        ),
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('repost', 'Repost'), ('quote', 'Quote')], default='post', max_length=15),
        ),
    ]
