# Generated by Django 5.2.1 on 2025-06-09 11:39

from django.db import migrations, models

def truncate_post_types(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    for post in Post.objects.all():
        if len(post.post_type) > 10:
            post.post_type = post.post_type[:10]
            post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_comment_image_remove_comment_reposts_and_more'),
    ]

    operations = [
        migrations.RunPython(truncate_post_types),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('repost', 'Repost'), ('quote', 'Quote')], default='post', max_length=15),
        ),
    ]
