# Generated by Django 5.2.1 on 2025-06-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_post_parent_post_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conversation_chain',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of post IDs in the conversation chain'),
        ),
    ]
