# Generated by Django 5.2.1 on 2025-06-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_post_conversation_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reposted_at',
            field=models.DateTimeField(blank=True, help_text='When this post was reposted by the current user', null=True),
        ),
    ]
