# Generated by Django 5.2.1 on 2025-06-13 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_post_reposted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reposters',
            field=models.ManyToManyField(blank=True, related_name='reposted_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
