# Generated by Django 5.2.1 on 2025-06-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_post_reposters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('reply', 'Reply'), ('repost', 'Repost'), ('quote', 'Quote'), ('human_art', 'Human Art')], default='post', max_length=15),
        ),
    ]
