# Generated by Django 5.2.1 on 2025-07-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_hashtag_posthashtag_post_hashtags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent_post_author_handle',
            field=models.CharField(blank=True, help_text='Handle of the parent post author for replies', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='parent_post_author_username',
            field=models.CharField(blank=True, help_text='Username of the parent post author for replies', max_length=100, null=True),
        ),
    ]
