# Generated by Django 5.2.1 on 2025-07-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_post_parent_post_author_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='When this post should be published. If null, post is published immediately.', null=True),
        ),
    ]
