# Generated by Django 5.2.1 on 2025-07-16 05:13

import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_postappeal_appealevidencefile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='Optional scheduled time for when this draft should be published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('reply', 'Reply'), ('repost', 'Repost'), ('quote', 'Quote')], default='post', max_length=15)),
                ('is_human_drawing', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
                ('parent_post', models.ForeignKey(blank=True, help_text='Parent post if this is a reply draft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_drafts', to='posts.post')),
                ('quote_post', models.ForeignKey(blank=True, help_text='Post being quoted in this draft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_in_drafts', to='posts.post')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=posts.models.draft_image_path)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.draft')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('scheduled_time', models.DateTimeField(help_text='When this post should be published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='scheduled', max_length=10)),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('reply', 'Reply'), ('repost', 'Repost'), ('quote', 'Quote')], default='post', max_length=15)),
                ('is_human_drawing', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to=settings.AUTH_USER_MODEL)),
                ('parent_post', models.ForeignKey(blank=True, help_text='Parent post if this is a reply', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_replies', to='posts.post')),
                ('published_post', models.ForeignKey(blank=True, help_text='The actual post created when this was published', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_source', to='posts.post')),
                ('quote_post', models.ForeignKey(blank=True, help_text='Post being quoted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_in_scheduled', to='posts.post')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=posts.models.scheduled_post_image_path)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.scheduledpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['author', '-updated_at'], name='posts_draft_author__6d7a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpost',
            index=models.Index(fields=['author', 'status', 'scheduled_time'], name='posts_sched_author__f98591_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpost',
            index=models.Index(fields=['status', 'scheduled_time'], name='posts_sched_status_73a18f_idx'),
        ),
    ]
