# Generated by Django 5.2.1 on 2025-08-24 07:16

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Whether this post has been removed due to violations'),
        ),
        migrations.AlterField(
            model_name='appealevidencefile',
            name='file',
            field=models.FileField(storage=posts.models.get_storage, upload_to=posts.models.appeal_evidence_path),
        ),
        migrations.AlterField(
            model_name='draftimage',
            name='image',
            field=models.ImageField(storage=posts.models.get_storage, upload_to=posts.models.draft_image_path),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='file',
            field=models.FileField(storage=posts.models.get_storage, upload_to=posts.models.evidence_file_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=posts.models.get_storage, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(storage=posts.models.get_storage, upload_to=posts.models.post_image_path),
        ),
        migrations.AlterField(
            model_name='scheduledpostimage',
            name='image',
            field=models.ImageField(storage=posts.models.get_storage, upload_to=posts.models.scheduled_post_image_path),
        ),
    ]