# Generated by Django 5.2.1 on 2025-06-02 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, help_text='A unique identifier for the user, used in mentions and URLs', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Handle can only contain letters, numbers, and underscores', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
