# Generated by Django 5.2.1 on 2025-06-02 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, help_text='Unique identifier for mentions (e.g. @handle)', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Handle can only contain letters, numbers, and underscores', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
