# Generated by Django 5.2.1 on 2025-06-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following_only_preference',
            field=models.BooleanField(default=False),
        ),
    ]
