# Generated by Django 5.2.1 on 2025-06-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_display_name'),
        ('users', '0011_user_following_only_preference'),
    ]

    operations = [
    ]
