# Generated by Django 5.2.1 on 2025-08-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20250613_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Spaces and unicode allowed.', max_length=150, unique=True),
        ),
    ]
